-- AlterTable
ALTER TABLE "Payslip"
    ADD COLUMN "overtimeAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN "cnssEmployer" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN "coutEmployeur" DOUBLE PRECISION NOT NULL DEFAULT 0;
